jobs:
  checkDocs:
    name: "Rendered 'docs/' is up to date"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: "actions/checkout@master"
        with:
          submodules: recursive
      - name: Install asdf
        uses: "asdf-vm/actions/setup@v1.0.0"
      - name: Install asdf plugins
        uses: scripts/ci/asdf-add-plugins.sh
      - name: Install asdf tools versions
        uses: scripts/ci/asdf-install.sh
      - name: "Check that 'docs' folder is up to date"
        run: scripts/ci/check-rendered-site-up-to-date.sh
  dhallFormat:
    name: dhall-format
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: "actions/checkout@master"
        with:
          submodules: recursive
      - name: Install asdf
        uses: "asdf-vm/actions/setup@v1.0.0"
      - name: Install asdf plugins
        uses: scripts/ci/asdf-add-plugins.sh
      - name: Install asdf tools versions
        uses: scripts/ci/asdf-install.sh
      - env:
          CHECK: 'true'
        name: Check that scripts are formatted consistently
        run: scripts/dhall-format.sh
  prettier:
    name: Prettier formatting
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: "actions/checkout@master"
        with:
          submodules: recursive
      - name: Install asdf
        uses: "asdf-vm/actions/setup@v1.0.0"
      - name: Install asdf plugins
        uses: scripts/ci/asdf-add-plugins.sh
      - name: Install asdf tools versions
        uses: scripts/ci/asdf-install.sh
      - name: Check Prettier formatting
        run: scripts/ci/check-prettier.sh
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: "actions/checkout@master"
        with:
          submodules: recursive
      - name: Install asdf
        uses: "asdf-vm/actions/setup@v1.0.0"
      - name: Install asdf plugins
        uses: scripts/ci/asdf-add-plugins.sh
      - name: Install asdf tools versions
        uses: scripts/ci/asdf-install.sh
      - name: Lint shell scripts
        run: scripts/ci/shellcheck.sh
  shfmt:
    name: shfmt
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: "actions/checkout@master"
        with:
          submodules: recursive
      - name: Install asdf
        uses: "asdf-vm/actions/setup@v1.0.0"
      - name: Install asdf plugins
        uses: scripts/ci/asdf-add-plugins.sh
      - name: Install asdf tools versions
        uses: scripts/ci/asdf-install.sh
      - name: Check that scripts are formatted consistently
        run: scripts/ci/shfmt.sh
name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
